- hosts: web-servers
  user: root
  roles:
    - { role: postfix, tags: postfix }
    - { role: common, tags: common}
    - httpd
    - ruby
    - nodejs
    - postgres
    - access
    - { role: SELinux, when: ansible_selinux.status == 'enabled' }
